### ISSUE TITLE
waitFor feature

### ISSUE THREAD

**Issue by treaz** [winsw/winsw#93] opened 2015-04-13 15:59 UTC
Hello,

great work on the service wrapper. Thank you :+1: 
Does it offer any mechanism that would actually keep the windows service in status starting until some trigger/callback event?

I'm wrapping a java application that starts up quite slowly and the wrapper returns the status started for the service before the application is fully initialized.

**Comment by kenny-evitt** [comment] 2015-04-17 15:50
I'm not sure you want to do this. Depending on how long your Java application takes to start, Windows may cancel starting the service if it exceeds its timeout. I expect the wrapper now returns a started status immediately because of that. See my older issue – #52 – for an example of problems that might be due to the service not finishing 'starting' immediately.

**Comment by treaz** [comment] 2015-04-17 17:05
I wonder if keeping the service in a starting state until everything is ready is something easy to do.
Something like this: https://www.devopsonwindows.com/avoid-windows-service-start-up-timeouts/

**Comment by oleg-nenashev** [comment] 2016-12-02 22:51
WinSW 2 offers an extension engine, so it likely could be implemented as an extension. But I have no plan to work on it in short-term. BTW, somebody could create a pull request

**Comment by NextTurn** [comment] 2020-07-29 11:13
> I wonder if keeping the service in a starting state until everything is ready is something easy to do.
> Something like this: https://www.devopsonwindows.com/avoid-windows-service-start-up-timeouts/

This is exactly what we do.

See my questions in #267 to complete a feature request.

According to #95, the author no longer works on Windows, so closing this as a dup.

Duplicate of #267

**Closed by NextTurn** 2020-07-29 11:13 UTC
Labels: enhancement, help wanted
