### ISSUE TITLE
jvisualvm or jmc does not detct jvms running as windows service

### ISSUE THREAD

**Issue by ksanjeev9211** [winsw/winsw#306] opened 2019-03-29 17:59 UTC

**Comment by oleg-nenashev** [comment] 2019-04-06 07:06
You would need to run Java tools with the same account as the service. Usually it is a system administrator unless your service runs under another account

**Comment by jvmlet** [comment] 2019-12-04 05:34
@ksanjeev9211 , please see this https://github.com/kohsuke/winsw/issues/150

**Comment by NextTurn** [comment] 2020-04-12 09:38
Closing as a duplicate of #150.

**Closed by NextTurn** 2020-04-12 09:38 UTC
Labels: question
