### ISSUE TITLE
Need Help On Using interactive Tag

### ISSUE THREAD

**Issue by arjuturu** [winsw/winsw#658] opened 2020-08-24 14:38 UTC
### Need Help On Using interactive Tag

I have a Java application which internally uses ProcesssBuilder to launch a xyz.exe application. This .exe opens a windows command prompt to execute the tasks. I have added "interactive" tag in the XML configuration then it asks me to open the window(GUI) which requires manual intervention while running the java application. I would like to know any option available along with "interactive" tag to open the window (GUI) without any manual intervention.

**Comment by NextTurn** [comment] 2020-08-24 14:45
Sorry I didn't get it. @oleg-nenashev Any insights that can help?

**Comment by arjuturu** [comment] 2020-08-24 15:13
@NextTurn I just updated my question.

**Comment by NextTurn** [comment] 2020-08-24 15:17
Is there Interactive Services Detection?

**Comment by arjuturu** [comment] 2020-08-24 15:39
Yes. Please refer screenshot
![15982833623162899433327157374989](https://user-images.githubusercontent.com/7734086/91065338-f8d80b80-e64d-11ea-966c-364d09e35124.jpg)

**Comment by NextTurn** [comment] 2020-08-25 02:23
Thanks for the additional context @arjuturu! On systems with Interactive Services Detection it's not possible to directly display windows of interactive services (so \<interactive\> doesn't make much sense). I'm closing this as a duplicate of the feature request #230.

**Closed by NextTurn** 2020-08-25 02:23 UTC
Labels: question
