### ISSUE TITLE
Request for wrapper.log debug loglevel deactivation

### ISSUE THREAD

**Issue by younid** [winsw/winsw#415] opened 2020-02-18 15:55 UTC
Hello,

This request just to ask if it's possible to disable or make configurable the log level for wrapper.log file.
It should be useful to be able to disable it when we run an application which riquires some credential or secret key in command line. For the moment the full command line is visible in the wrapper.log file generated and not concerned by the log mode set to none in parameters.

Looking in the code I found that this level is hard coded and not a parameter :
```
        private static void InitLoggers(ServiceDescriptor d, bool enableCLILogging)
        {
            // TODO: Make logging levels configurable
            Level logLevel = Level.Debug;

```

Thank you in advance for your help.

Regards

**Comment by nchevsky** [comment] 2020-06-06 07:02
I recommend that this be closed as a duplicate of #39.

**Comment by oleg-nenashev** [comment] 2020-06-06 07:04
Agreed, this is a duplicate

**Closed** 2020-06-06 07:05 UTC
Labels: duplicate

**Comment by NextTurn** [comment] 2020-08-02 00:05
Unrelated to #39, I've removed logging command line arguments.
