### ISSUE TITLE
Wrong getting process child happend.

### ISSUE THREAD

**Issue by Lexus-3141** [winsw/winsw#123] opened 2016-10-12 13:37 UTC
Hi, i'm using winsw for running consul application as winservice. 
I found that consul.exe was running, but in mmc.exe it had status "stopped" on 50% of my servers. 
## This exeption was found in log:

2016-10-10 03:18:53 - Starting consul.exe agent -config-file consul.conf
2016-10-10 03:18:53 - Started 18192
2016-10-10 03:35:01 - Stopping consul-agent
2016-10-10 03:35:01 - ProcessKill 18192
2016-10-10 03:35:02 - Found child process: 7852 Name: conhost.exe
2016-10-10 03:35:02 - Stopping process 7852
2016-10-10 03:35:02 - Send SIGINT 7852
2016-10-10 03:35:02 - SIGINT to 7852 failed - Killing as fallback
2016-10-10 03:35:02 - Stopping process 18192
2016-10-10 03:35:02 - Send SIGINT 18192
2016-10-10 03:35:02 - SIGINT to 18192 failed - Killing as fallback
2016-10-10 03:35:02 - Finished consul-agent
2016-10-10 03:35:06 - Starting consul.exe agent -config-file consul.conf
2016-10-10 03:35:06 - Started 7560
2016-10-10 03:51:54 - Stopping consul-agent
2016-10-10 03:51:54 - ProcessKill 7560
2016-10-10 03:51:55 - Found child process: 8052 Name: conhost.exe
2016-10-10 03:51:55 - Found child process: 14520 Name: csrss.exe
2016-10-10 03:51:55 - Found child process: 12208 Name: winlogon.exe
2016-10-10 03:51:55 - Stopping process 14520
2016-10-10 03:51:55 - Send SIGINT 14520
2016-10-10 03:51:55 - SIGINT to 14520 failed - Killing as fallback
2016-10-10 03:51:55 - Stop exception
Message:Access is denied
Stacktrace:   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at winsw.WrapperService.StopProcess(Int32 pid)
   at winsw.WrapperService.StopProcessAndChildren(Int32 pid)
   at winsw.WrapperService.StopProcessAndChildren(Int32 pid)
   at winsw.WrapperService.StopProcessAndChildren(Int32 pid)
   at winsw.WrapperService.StopIt()
   at winsw.WrapperService.OnStop()

**Comment by Lexus-3141** [comment] 2016-10-12 13:49
Hmm, am using an old version winsw - 1.18.0.  I'll try to using 2.0..

**Comment by oleg-nenashev** [comment] 2016-10-12 14:03
Most likely winsw 2 will fail as well. (it has not been released yet BTW).
But maybe there will be more diagnostics info

**Comment by oleg-nenashev** [comment] 2016-11-26 22:04
Due to whatever reason WinSW has no permission to kill one of the child processes. and SIGINT did not work. And SIGINT wait interval is too small due to whatever reason

**Comment by oleg-nenashev** [comment] 2016-12-09 11:34
I assume it has be fixed by #135 (if the process gracefully exits)

**Comment by oleg-nenashev** [comment] 2017-01-11 10:48
There are also fixes around process termination in #166, #59, #159. #166 could be a good candidate.

Please try `2.0.1` and let me know if it fixes the issue

**Comment by astryia** [comment] 2018-07-24 12:19
I'm using winsw 2.1.2 and encountered  the same problem:
```
2018-07-24 11:22:28,165 INFO  - Found child process: 612 Name: csrss.exe
2018-07-24 11:22:28,165 INFO  - Found child process: 648 Name: winlogon.exe
2018-07-24 11:22:28,236 INFO  - Found child process: 11092 Name: mesos-component-executor.exe
2018-07-24 11:22:28,255 INFO  - Stopping process 612
2018-07-24 11:22:28,256 INFO  - Send SIGINT 612
2018-07-24 11:22:28,256 WARN  - SIGINT to 612 failed - Killing as fallback
2018-07-24 11:22:28,257 ERROR - Cannot stop exception
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.get_HasExited()
   at winsw.Util.ProcessHelper.StopProcess(Int32 pid, TimeSpan stopTimeout)
   at winsw.Util.ProcessHelper.StopProcessAndChildren(Int32 pid, TimeSpan stopTimeout, Boolean stopParentProcessFirst)
   at winsw.Util.ProcessHelper.StopProcessAndChildren(Int32 pid, TimeSpan stopTimeout, Boolean stopParentProcessFirst)
   at winsw.Util.ProcessHelper.StopProcessAndChildren(Int32 pid, TimeSpan stopTimeout, Boolean stopParentProcessFirst)
   at winsw.WrapperService.StopIt()
   at winsw.WrapperService.OnStop()
```
 I think, the reason is the way how you search the child processes: 
```
var searcher = new ManagementObjectSearcher("Select * From Win32_Process Where ParentProcessID=" + pid);
```
csrss.exe and winlogon.exe could not be the child  of the service process.

Client/Server Runtime Subsystem (CSRSS or csrss.exe) is spawned by the Session Manager Subsystem (SMSS or smss.exe). SMSS is spawned by System (which always has a PID of 4) under Session 0 for OS services. Additionally, SMSS is spawned in Session 1 (the user session) with the sole job of starting CSRSS and WININIT. Once those two are started, the Session 1 SMSS terminates.

Windows can reuse PID of stopped processes and reassign it to the new one, but ParentProcessID filed is  not updated. That's why WMI query can return 'false positive' child.

You can just compare process creation time to see if the children are newer then the parent.

**Comment by minghuijiang** [comment] 2018-08-07 15:52
We had the same issue when winsw search and return the wrong child list.

**Closed** 2020-07-17 02:07 UTC
Labels: bug

**Comment by dave-q** [comment] 2020-08-26 21:00
Hi @NextTurn I noticed that the PR to check the start time of the potential child process has been merged, which I'm assuming stops the issue where it tries to uninstall some random service.

However I'm guessing that in this scenario a child service is still left running and orphaned right? We are seeing this currently, we want to stop the service thats been wrapped and uninstall it, but we can't because a file the service uses is locked by Java (a child process of the service I believe) and has not been killed.

Any thoughts on how we get around that?

**Comment by NextTurn** [comment] 2020-08-27 00:05
@dave-q WinSW version?

**Comment by dave-q** [comment] 2020-08-27 08:16
Version 2.4.0 according to the executable I've been working with

**Comment by NextTurn** [comment] 2020-08-27 08:25
> Version 2.4.0 according to the executable I've been working with

The fix for the issue is only available in WinSW 3 at the moment.

**Comment by dave-q** [comment] 2020-08-27 08:54
The fix in version 3 stops the wrong process being kill right? But am I right in thinking that if the PID has changed the real child process ends up orphaned and left running right?

Also do you know that the .net implementation of Process.Kill has a Boolean to indicate killing the tree that does a pretty similar thing to what your change does

**Comment by NextTurn** [comment] 2020-08-27 09:04
> But am I right in thinking that if the PID has changed...

Can you clarify?

> Also do you know that the .net implementation of Process.Kill has a Boolean to indicate killing the tree that does a pretty similar thing to what your change does 

microsoft/azure-pipelines-agent#3074

**Comment by dave-q** [comment] 2020-08-27 09:13
I'm not 100% sure really how it's happening but our wrapper is wrapping a Jar file so when it runs it it starts Java at some point in the future we stop the wrapper service it throws the exception because it tries to stop some random process that it can't and leaves Java running meaning when we get delete the jar and it's dependencies it fails because Java is still using one.

Is this just happening because an exception is thrown before it can stop the Java process or does it no longer know about the Java process and some how has the wrong PID?

Also fyi it looks like the dot net implementation has changed a bit but still stops them children first it appears 
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs
See IsParentOf on line 346 
- thought you might find it interesting

**Comment by NextTurn** [comment] 2020-08-27 09:35
> Is this just happening because an exception is thrown before it can stop the Java process

Yep. The exception crashes the wrapper, and the Java process is not stopped because child processes are stopped first by default.

**Comment by dave-q** [comment] 2020-08-27 09:40
Ah ok this is making more sense now. Really appreciate your time and help, thanks
