### ISSUE TITLE
Silencing Application event log entries?

### ISSUE THREAD

**Issue by theultramage** [winsw/winsw#278] opened 2018-06-14 00:00 UTC
Everytime the service starts and stops, it writes multiple entries into the Application event log, including the full commandline, twice, and a warning about a SIGINT timeout. This adds a lot of pointless noise into the log. Is there a way to disable this logging?

**Comment by theultramage** [comment] 2018-07-30 06:18
````<log mode="none"/>```` is present in my configuration file, that's why I submitted this issue. Somehow I forgot to include this fact.

**Comment by oleg-nenashev** [comment] 2018-07-30 06:31
`log mode="none"` addresses only logging to the disk, but it does not impact event logs in the legacy code within WinSW. #213 is probably a solution, assuming I ever got it over the fence (hope so)

**Comment by NextTurn** [comment] 2020-07-23 06:41
Duplicate of #241

**Closed by NextTurn** 2020-07-23 06:41 UTC
