### ISSUE TITLE
Wrong version reported by winsw executable

### ISSUE THREAD

**Issue by fkleon** [winsw/winsw#488] opened 2020-04-07 05:07 UTC
**The version announced by the winsw executable is incorrect**. Running `winsw.exe version` or `winsw.exe help` prints `WinSW 1.0.0.0` instead of the correct version.

## Steps to reproduce

Download winsw release >= 4.6.0, use provided minimal XML config file, run `winsw.exe version`.

* Actual output: `WinSW 1.0.0.0`
* Expected output: `WinSW 4.6.0.0` (or appropriate)

## Environment

* WinSW version: 2.6.0 to 2.7.0
* WinSW package type: .NET 4.6.1 
* Windows version: Windows Server 2008 R2 Enterprise
* Wrapped executable and version: Java

**Comment by NextTurn** [comment] 2020-04-07 05:21
We're moving away from AppVeyor. Will be fixed by #477 and following ones.

**Comment by oleg-nenashev** [comment] 2020-04-07 07:01
If this happens on 4.6.0, it is not related to the recent Appveyor migration. Maybe it is caused by project restructuring.

Anyway, I agree that we should get Azure DevOps pipeline over the line and fix it there

**Closed** 2020-04-08 10:08 UTC
Labels: bug
