### ISSUE TITLE
service does not start - 'The process ID is invalid'

### ISSUE THREAD

**Issue by mrt181** [winsw/winsw#265] opened 2018-02-07 12:13 UTC
I followed the instructions but my spring-boot service does not start.

The error in the event log is this:

> An unhandled exception ('System.UnauthorizedAccessException') occurred in process #16044. Just-In-Time debugging this exception failed with the following error: The process ID is invalid.
> 
> Check the documentation index for 'Just-in-time debugging, errors' for more information.

These are the commands I use from an administrator cmd:

```
C:\neCOMancer\winsw>neCOMancer.exe version
WinSW 2.1.2.0

C:\neCOMancer\winsw>neCOMancer.exe install
2018-02-07 12:42:11,599 INFO  - Installing the service with id 'neCOMancer'

C:\neCOMancer\winsw>neCOMancer.exe test
2018-02-07 12:42:28,493 INFO  - Starting java -server -Xms1g -Xmx4g -jar neCOMancer-0.7.6-SNAPSHOT.jar
2018-02-07 12:42:28,493 INFO  - Starting java -server -Xms1g -Xmx4g -jar neCOMancer-0.7.6-SNAPSHOT.jar
2018-02-07 12:42:28,540 INFO  - Started process 16216
2018-02-07 12:42:29,557 INFO  - Stopping neCOMancer
2018-02-07 12:42:29,682 INFO  - Stopping process 16216
2018-02-07 12:42:29,698 INFO  - Send SIGINT 16216
2018-02-07 12:42:29,698 WARN  - SIGINT to 16216 failed - Killing as fallback
2018-02-07 12:42:29,713 INFO  - Finished neCOMancer

C:\neCOMancer\winsw>neCOMancer.exe start
2018-02-07 12:45:22,853 INFO  - Starting the service with id 'neCOMancer'

```
In the windows event log I see that it logs the service start twice - `Starting java ...`?
Then it logs `Service started successfully.`
Then the error occurs.
The same error occurs when I start the service manually via `services.msc` or `sc start neCOMancer`

my process is still started for some seconds before it disappears from taskmgr and also the vsjitdebugger process is also started:
```
java.exe  0.02	2,169,768 K	721,808 K	11512	Java(TM) Platform SE binary	Oracle Corporation	"java" -server -Xms1g -Xmx4g -jar neCOMancer-0.7.6-SNAPSHOT.jar
vsjitdebugger.exe	Suspended	320 K	232 K	17048	Visual Studio Just-In-Time Debugger	Microsoft Corporation	"C:\WINDOWS\system32\vsjitdebugger.exe" PID 15928 APPDOM 1 EXTEXT "System.UnauthorizedAccessException" EVTHDL 756
```

If I just issue this command the service starts:
```
C:\neCOMancer\winsw>java -server -Xms1g -Xmx4g -jar neCOMancer-0.7.6-SNAPSHOT.jar
```

**Comment by oleg-nenashev** [comment] 2018-03-02 08:47
Double logging may happen due to the logging subsystem initialization in some cases:

```
https://github.com/kohsuke/winsw/blob/d98bb9e9adfb5c185211aa1c765481967e1056c7/src/Core/ServiceWrapper/Main.cs#L241-L242
```

OTOH is should not. Will check it.

However, I doubt it is related to the issue:

```
An unhandled exception ('System.UnauthorizedAccessException') occurred in process #16044. Just-In-Time debugging this exception failed with the following error: The process ID is invalid.
```

Do you have a full stackrace for it? It appears to be a .NET exception though it likely comes from the vsjitdebugger instance

My theory:

* An application crashes due to whatever reason
* Your operating system is configured to automatically start a debugger on crash
* vsjitdebugger has no permission to debug services, and it fails with this error message

**Comment by NextTurn** [comment] 2020-07-17 09:25
Duplicate of #198

**Closed by NextTurn** 2020-07-17 09:25 UTC
